services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
   
    env_file:
      - .env
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
